model:
  base_learning_rate: 1.0e-5
  target: ldm.models.autoencoder.VQFlowNet
  params:
    monitor: val/total_loss
    embed_dim: 3
    n_embed: 16384
    ddconfig:
      double_z: False
      z_channels: 8
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1,2,2,2,4]  # f = 2 ^ len(ch_mult)
      num_res_blocks: 1
      cond_type: max_cross_attn
      attn_type: max
      attn_resolutions: [16]
      dropout: 0.0
      load_VFI: ## path to VFIformer weights

    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.5
        codebook_weight: 1.0 
        perceptual_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.bvi_vimeo.Vimeo90k_triplet
      params:
        db_dir: ...../data/vimeo_triplet ## path to vimeo_triplet
        crop_sz: [256,256]
        iter: True
    validation:
      target: ldm.data.bvi_vimeo.Vimeo90k_triplet
      params:
        db_dir: ..../data/vimeo_triplet ## path to vimeo_triplet
        train: False
        crop_sz: [256,256]
        augment_s: False
        augment_t: False


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 10000
        val_batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        log_images_kwargs: {'N': 1}

  trainer:
    benchmark: True
    max_epochs: -1
